name: easy_xchange
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  nb_utils: ^7.0.3
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.1
  salomon_bottom_bar: ^3.3.2
  change_app_package_name: ^1.2.0
  email_otp: ^3.0.2
  url_launcher: ^6.3.1
  path_provider: ^2.0.5

  # google
  google_sign_in: ^6.2.2
  google_fonts: ^4.0.1 



# firebase
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1 
  permission_handler: ^11.4.0
  flutter_spinkit: ^5.2.1
  # supabase
  supabase_flutter: ^2.8.4 
  
  # map
  google_maps_flutter: ^2.12.1
  location: ^8.0.0 
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  app_settings: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/svgIcons/

