// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlaYnanh-74tSKfOtL2mUZIOoSN5A4kGU',
    appId: '1:576669009925:web:6a6088c45875b8a601b46c',
    messagingSenderId: '576669009925',
    projectId: 'muzahirfyp',
    authDomain: 'muzahirfyp.firebaseapp.com',
    storageBucket: 'muzahirfyp.appspot.com',
    measurementId: 'G-NT2NM2QTX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigyTqneYC7uPE-zGV-696ljrVzZUp3tE',
    appId: '1:818944319790:android:0d010f8f4806c9bab75abf',
    messagingSenderId: '818944319790',
    projectId: 'easy-xchange-57263',
    storageBucket: 'easy-xchange-57263.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlaYnanh-74tSKfOtL2mUZIOoSN5A4kGU',
    appId: '1:576669009925:web:3706304548dcd76b01b46c',
    messagingSenderId: '576669009925',
    projectId: 'muzahirfyp',
    authDomain: 'muzahirfyp.firebaseapp.com',
    storageBucket: 'muzahirfyp.appspot.com',
    measurementId: 'G-BTP6ZEX12H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBh-QZW3BfLPtpg2e9KzrukRhl7my5F4E',
    appId: '1:818944319790:ios:9fd0bc8808ce191db75abf',
    messagingSenderId: '818944319790',
    projectId: 'easy-xchange-57263',
    storageBucket: 'easy-xchange-57263.firebasestorage.app',
    iosBundleId: 'com.example.cashNew',
  );

}